# Generated by Django 4.2.7 on 2023-12-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(default=1, max_length=10, verbose_name='Технологическая специализация'),
            preserve_default=False,
        ),
    ]
