# Generated by Django 4.2.7 on 2023-12-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_of_residence',
            field=models.CharField(default=1, max_length=255, verbose_name='Город проживания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Технологическая специализация'),
        ),
    ]
