# Generated by Django 4.2.7 on 2023-12-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city_of_residence_alter_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(default=1, max_length=255, verbose_name='Страна проживания'),
            preserve_default=False,
        ),
    ]
