# Generated by Django 4.2.7 on 2023-12-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_country_of_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка на профиль GitHub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка на сайт'),
            preserve_default=False,
        ),
    ]
