# Generated by Django 4.2.7 on 2023-12-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_github_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=1, max_length=255, verbose_name='Образование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('Ищу работу', 'Ищу работу'), ('Трудоестроен', 'Трудоестроен')], default=1, max_length=255, verbose_name='Трудовой статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(default=1, max_length=255, verbose_name='Место работы'),
            preserve_default=False,
        ),
    ]
