# Generated by Django 4.2.7 on 2023-12-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='Краткое описание для превью'),
        ),
    ]
