# Generated by Django 4.2.7 on 2023-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foreign_languages',
            field=models.CharField(default=1, max_length=255, verbose_name='Перечислите через запятую языки, которыми владеете'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='publications',
            field=models.TextField(blank=True, verbose_name='Публикации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(max_length=255, verbose_name='Перечислите через запятую hard и soft skills, которыми владете'),
        ),
    ]
