# Generated by Django 4.2.7 on 2023-12-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_image',
            field=models.ImageField(default=1, upload_to='article_img/'),
            preserve_default=False,
        ),
    ]
