# Generated by Django 4.2.7 on 2023-12-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_image',
        ),
    ]
