# Generated by Django 4.2.7 on 2023-12-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Мета теги'),
        ),
    ]
