# Generated by Django 4.2.7 on 2023-12-27 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_articlecomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComments',
            new_name='Comments',
        ),
    ]
