# Generated by Django 4.2.7 on 2023-12-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_author',
            new_name='author',
        ),
    ]
