# Generated by Django 4.2.7 on 2023-12-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_comment_author_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.IntegerField(),
        ),
    ]
