# Generated by Django 4.2.7 on 2023-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_comments_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.IntegerField(),
        ),
    ]
