# Generated by Django 4.2.7 on 2023-12-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_comments_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
    ]
