# Generated by Django 4.2.7 on 2023-12-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_remove_comments_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
