# Generated by Django 4.2.7 on 2023-12-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_comments_article_comments_parent_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
