# Generated by Django 4.2.7 on 2024-01-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
