# Generated by Django 4.2.7 on 2024-01-03 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
