# Generated by Django 4.2.7 on 2024-01-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_comments_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
    ]
