# Generated by Django 4.2.7 on 2024-01-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_comments_parrent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parrent_id',
            field=models.IntegerField(),
        ),
    ]
