# Generated by Django 4.2.7 on 2024-01-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_comments_parrent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parrent_id',
            new_name='parent_id',
        ),
    ]
