# Generated by Django 4.2.7 on 2024-01-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_comments_level_comments_lft_comments_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
